### ISSUE TITLE
怎么配置

### ISSUE THREAD

**Issue by gs-liut** [zxavier94/svn-publisher#1]
怎么配置

**Comment by zxavier94** [comment]
我刚写在博客中 https://www.cnblogs.com/ZMargo/articles/11652854.html

**Comment by jadewei** [comment]
请问Test connection 这个按钮有用吗

**Comment by jadewei** [comment]
这个插件是不是不能用了

**Comment by zxavier94** [comment]
> 这个插件是不是不能用了

![image](https://user-images.githubusercontent.com/19486599/81780597-5b871a80-9529-11ea-9227-6c00937af6c2.png)
一直是有用的，公司内部一直在用的

**Comment by zxavier94** [comment]
https://www.cnblogs.com/ZMargo/articles/11652854.html
